"""added journal fields

Revision ID: 176e5726f81a
Revises: b2ef08d54a9d
Create Date: 2026-02-05 18:19:00.003896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176e5726f81a'
down_revision: Union[str, Sequence[str], None] = 'b2ef08d54a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('journals', sa.Column('mood_tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'mood_tag')
    op.drop_column('journals', 'title')
    # ### end Alembic commands ###
