"""empty message

Revision ID: 8e3063b174c9
Revises: 176e5726f81a
Create Date: 2026-02-06 15:30:08.355693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3063b174c9'
down_revision: Union[str, Sequence[str], None] = '176e5726f81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memories_source_journal_id_fkey'), 'memories', type_='foreignkey')
    op.create_foreign_key(None, 'memories', 'journals', ['source_journal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.create_foreign_key(op.f('memories_source_journal_id_fkey'), 'memories', 'journals', ['source_journal_id'], ['id'])
    # ### end Alembic commands ###
