"""added memories and updated journals

Revision ID: b2ef08d54a9d
Revises: 118369b5898f
Create Date: 2026-02-04 18:49:20.425007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2ef08d54a9d'
down_revision: Union[str, Sequence[str], None] = '118369b5898f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('source_journal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('journals', sa.Column('is_saved', sa.Boolean(), nullable=True))
    op.alter_column('journals', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('journals', 'updated_at')
    op.drop_column('journals', 'title')
    op.drop_column('journals', 'mood_tag')
    op.drop_column('journals', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('mood_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('journals', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('journals', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('journals', 'is_saved')
    op.drop_table('memories')
    # ### end Alembic commands ###
