"""add trigger category

Revision ID: f8b02f2b5e6f
Revises: ea91cab0ba63
Create Date: 2026-03-31 00:22:37.074102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b02f2b5e6f'
down_revision: Union[str, Sequence[str], None] = 'ea91cab0ba63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('trigger_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'trigger_category')
    # ### end Alembic commands ###
